// hinf_coeffs.h — auto-generated by coeffs_analyze.py
// Q3.29  5 sections  fs=0.9766 MHz  quant err -69.9 dB
// HLS arithmetic check: AP_TRN_ZERO, step +50: fx +0, float +17.30, maxerr 17.3; step -50: fx +0, float -17.30, maxerr 17.3
#ifndef HINF_COEFFS_H
#define HINF_COEFFS_H
#include <stdint.h>

#define HINF_N_SECTIONS     5
#define HINF_COEF_INT_BITS  3
#define HINF_COEF_FRAC_BITS 29
#define HINF_COEF_SCALE     536870912L

typedef struct { int32_t b0,b1,b2,a1,a2; } hinf_sos_t;

static const hinf_sos_t HINF_SOS[5] = {
    {   10141500,   -3249108,          0,  517782085,          0},
    {  536870912,-1038862934,  502480541,-1059503825,  522641849},
    {  536870912,-1072909528,  536757051,-1072927253,  536781896},
    {  536870912,-1073283251,  536778778,-1073293115,  536794454},
    {  536870912,-1073560906,  536834586,-1073552977,  536827565}
};

#endif
