// hinf_coeffs.h — auto-generated by coeffs_analyze.py
// Q4.28  6 sections  fs=0.9766 MHz  quant err -52.8 dB
// HLS arithmetic check: AP_TRN_ZERO, step +50: fx +0, float +0.66, maxerr 78.9; step -50: fx +0, float -0.66, maxerr 78.9
#ifndef HINF_COEFFS_H
#define HINF_COEFFS_H
#include <stdint.h>

#define HINF_N_SECTIONS     6
#define HINF_COEF_INT_BITS  4
#define HINF_COEF_FRAC_BITS 28
#define HINF_COEF_SCALE     268435456L

typedef struct { int32_t b0,b1,b2,a1,a2; } hinf_sos_t;

static const hinf_sos_t HINF_SOS[6] = {
    {  932784050,-1726697792,  793913884, -503474883,  236472737},
    {  268435456, -519431527,  251240330, -261475156,          0},
    {  268435456, -536454763,  268378525, -536446123,  268374039},
    {  268435456, -536641627,  268389390, -536646245,  268397111},
    {  268435456, -536780452,  268417292, -536776470,  268413767},
    {  268435456,  268435456,          0,     125549, -268302004}
};

#endif
