// hinf_coeffs.h — auto-generated by coeffs_analyze.py
// Q3.21  3 sections  fs=0.9766 MHz  quant err -50.3 dB
#ifndef HINF_COEFFS_H
#define HINF_COEFFS_H
#include <stdint.h>

#define HINF_N_SECTIONS     3
#define HINF_COEF_INT_BITS  3
#define HINF_COEF_FRAC_BITS 21
#define HINF_COEF_SCALE     2097152L

typedef struct { int32_t b0,b1,b2,a1,a2; } hinf_sos_t;

static const hinf_sos_t HINF_SOS[3] = {
    {    4268706,    1879678,          0,     923782,          0},
    {    2097152,   -3322354,    1230708,   -3964580,    1867792},
    {    2097152,   -4181781,    2085281,   -4191448,    2094883}
};

#endif
